window.AutopilotControls = ({state,spec,escape,icon}) => {
  const toggle = key => {
    const field=spec.fields.find(f=>f.key===key);
    const label=field.label.replace(/\s*\(experimental\)/i,'');
    return `<div class="setting-row"><label class="setting-toggle" for="field-${key}"><span class="setting-name">${escape(label)}${key==='allowConceptPlayers'?'<span class="beta-mark" title="Experimental">β</span>':''}</span><span class="switch"><input type="checkbox" id="field-${key}" data-key="${key}" ${state.draft[key]?'checked':''}><span class="switch-track"></span></span></label><button class="field-help" data-help="${key}" aria-label="About ${escape(label)}" aria-expanded="false" aria-controls="help-${key}">?</button><p class="field-description" id="help-${key}" hidden>${escape(field.help)}${key==='allowConceptPlayers'?' Concept players must be owned before submission. Points SBCs use owned players only.':''}</p></div>`;
  };
  const rating=()=>{
    const {ratingMin:low,ratingMax:high}=state.draft.ratingRange;
    return `<section class="rating-editor" aria-label="Player rating range"><div class="rating-heading"><strong>Player rating range</strong><output data-rating-summary aria-live="off">${low}<span>–</span>${high}<small>OVR</small></output></div><div class="rating-control" style="--low:${low/99*100}%;--high:${high/99*100}%"><div class="rating-scale" data-rating-rail><div class="rating-quality bronze-band"></div><div class="rating-quality silver-band"></div><div class="rating-quality gold-band"></div><div class="rating-selection"></div><button type="button" role="slider" class="rating-handle low-handle" data-rating-handle="ratingMin" aria-label="Minimum player rating" aria-valuemin="0" aria-valuemax="${high}" aria-valuenow="${low}" aria-valuetext="${low} OVR minimum"><span></span></button><button type="button" role="slider" class="rating-handle high-handle" data-rating-handle="ratingMax" aria-label="Maximum player rating" aria-valuemin="${low}" aria-valuemax="99" aria-valuenow="${high}" aria-valuetext="${high} OVR maximum"><span></span></button></div></div><div class="rating-ticks" aria-hidden="true"><span>0</span><span style="left:${64/99*100}%">64</span><span style="left:${74/99*100}%">74</span><span>99</span></div><div class="rating-legend"><span><i class="bronze-dot"></i>Bronze ≤64</span><span><i class="silver-dot"></i>Silver 65–74</span><span><i class="gold-dot"></i>Gold 75+</span></div><div class="rating-footer"><div class="rating-context">Drag either handle. Arrow keys adjust by 1 OVR.</div><button type="button" class="preset-button" data-preset-toggle aria-expanded="false" aria-controls="rating-presets">Rating presets ▾</button><div class="preset-list" id="rating-presets" data-rating-presets hidden aria-label="Rating presets"><button type="button" data-rating-preset="all"><span>All ratings</span><small>0–99 OVR</small></button><button type="button" data-rating-preset="bronze"><span>Bronze</span><small>0–64 OVR</small></button><button type="button" data-rating-preset="silver"><span>Silver</span><small>65–74 OVR</small></button><button type="button" data-rating-preset="gold"><span>Gold</span><small>75–99 OVR</small></button></div></div></section>`;
  };
  const buckets=()=>`<fieldset class="bucket-editor"><legend><span>Base card types</span><span data-bucket-count>${state.draft.allowedCardBuckets.length} / 6 enabled</span></legend><div class="card-matrix"><span></span>${['bronze','silver','gold'].map(q=>`<span class="quality-title ${q}"><span class="quality-symbol"></span>${q.charAt(0).toUpperCase()+q.slice(1)}</span>`).join('')}${['common','rare'].map(rarity=>`<span class="rarity-title">${rarity==='rare'?'Rare':'Common'}</span>${['bronze','silver','gold'].map(quality=>{const key=rarity+'_'+quality;return `<label class="card-cell ${quality}"><input type="checkbox" data-bucket="${key}" aria-label="Allow ${rarity} ${quality}" ${state.draft.allowedCardBuckets.includes(key)?'checked':''}><span class="card-cell-check">${icon('check')}</span></label>`;}).join('')}`).join('')}</div><p class="bucket-limit" data-bucket-limit hidden>Keep at least one card type enabled.</p></fieldset>`;
  return {toggle,rating,buckets};
};
