"""Freeze the approved Design 2 controls/styles as isolated extension assets."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
design = root / 'artifacts/autopilotsbc-tab-designs'
controls = (design / 'selected-controls.js').read_text(encoding='utf-8')
controls = controls[controls.index(' const {state,spec,escape,icon}=context;'):]
controls = controls[:controls.rindex(' return {...base,toggle,rating,buckets};')]
# Keyboard limits are normal slider behavior. Keep the help static and accurate.
controls = controls.replace(" const ceiling=high>=99?'':` Maximum stops at ${high}.`;", '')
controls = controls.replace('Arrow keys move by 1 OVR.${ceiling}', 'Arrow keys move by 1 OVR within the range.')
(root / 'page/autopilot-settings-controls.js').write_text(
    '// Controls from approved Design 2. Generated by scripts/build-settings-assets.py.\n'
    '(() => {\n  window.AutopilotSettingsControls = context => {\n' + controls +
    '\n    return {toggle,rating,buckets};\n  };\n})();\n', encoding='utf-8')
controls_path = root / 'page/autopilot-settings-controls.js'
controls_path.write_text(''.join(c if ord(c) < 128 else f'\\u{ord(c):04x}'
    for c in controls_path.read_text(encoding='utf-8')), encoding='utf-8')

css = '\n'.join((design / f).read_text(encoding='utf-8') for f in
                ['controls.css', 'tab-refinement.css', 'selected.css', 'palette.css'])
css = css.replace(':root', ':host').replace('body[data-design=guided]', '.autopilot-settings[data-design=guided]')
css = css.replace('body ', '.autopilot-settings ')
css += '''
/* Native view sizing. Everything in this stylesheet lives inside a shadow root. */
:host{display:block;position:absolute;inset:0;min-width:0;min-height:0;color-scheme:dark}
.autopilot-settings{height:100%;min-height:0;container-type:inline-size;background:#101820;font-family:Arial,'Segoe UI',sans-serif;color:#eff6f7;font-size:14px;line-height:1.45}
.autopilot-settings[data-design=guided]{--frame-width:min(920px,calc(100cqw - 56px));--rail-width:0px}
.autopilot-settings .workspace-head{background:transparent}
.autopilot-settings .rating-zone,.autopilot-settings .card-zone,.autopilot-settings .preference-zone,.autopilot-settings .exclusion-zone{padding-inline:30px}
.autopilot-settings .page-scroll{display:flex;flex-direction:column}
.autopilot-settings .workspace-head{flex:none}
.autopilot-settings .content-frame{display:flex;flex-direction:column;flex:1 0 auto;min-height:0}
.autopilot-settings .tab-page{margin-bottom:16px}
.autopilot-settings .project-footer{margin-top:auto;padding-top:18px}
.autopilot-settings .project-footer-frame{width:100%}
.autopilot-settings .preference-zone h2,.autopilot-settings .bucket-editor legend,.autopilot-settings .exclusion-heading h3,.autopilot-settings .rating-heading strong{font-size:16px;font-weight:600;letter-spacing:-.2px;text-transform:none;color:#eff6f7}
.autopilot-settings .rating-instruction,.autopilot-settings .bucket-limit{font-size:12px;line-height:1.5}
.autopilot-settings .savebar .save-utility .reset-action{border-color:transparent;color:#c9a197}
.autopilot-settings .savebar .save-utility .reset-action:hover{color:#ffd3c6}
.autopilot-settings .exclusion-choice:hover .exclusion-state{border-color:#7295a4;color:#e2f6f0}
.autopilot-settings .search-field{display:flex;align-items:center;gap:12px;padding:0 14px}
.autopilot-settings .search-field input{background:none;border:0;padding:12px 0;width:100%;min-width:0;color:inherit;outline-offset:0}
.autopilot-settings .exclusion-player-meta{display:block;font-size:11px;color:#a5bcc7;margin-top:3px}
.autopilot-settings .exclusion-emblem.asset-emblem{clip-path:none;background:transparent;width:40px;height:40px;color:#a5bcc7}
.autopilot-settings .asset-emblem img{display:block;width:100%;height:100%;object-fit:contain}
.autopilot-settings .asset-fallback{display:grid;place-items:center;width:100%;height:100%}
.autopilot-settings .asset-emblem.has-asset .asset-fallback{display:none}
.autopilot-settings .ui-notice{margin-top:14px;min-height:18px;font-size:12px;color:#a4c7ba}
.autopilot-settings .ui-notice:empty{display:none}
.autopilot-settings .ui-notice.error{color:#f3baa7}
.autopilot-settings .pending-note{display:none;color:#edce89;font-size:12px;padding:12px 0 0}
.autopilot-settings .pending-note:not(:empty){display:block}
.autopilot-settings dialog{max-width:min(440px,calc(100% - 32px));padding:24px;border:1px solid #456572;border-radius:12px;background:#1a2d39;color:#edf5f8}
.autopilot-settings dialog::backdrop{background:#06101bcc}
.autopilot-settings dialog h2{font-size:18px;margin-bottom:10px}
.autopilot-settings dialog p{font-size:13px;line-height:1.6;color:#bad0d9}
.autopilot-settings dialog .dialog-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px}
.autopilot-settings [hidden]{display:none!important}
@media(max-width:600px){
 .autopilot-settings[data-design=guided]{--frame-width:calc(100cqw - 32px)}
 .autopilot-settings .rating-zone,.autopilot-settings .card-zone,.autopilot-settings .preference-zone,.autopilot-settings .exclusion-zone{padding-inline:18px}
 .autopilot-settings .preference-zone h2,.autopilot-settings .bucket-editor legend,.autopilot-settings .exclusion-heading h3{font-size:15px}
 .autopilot-settings .rating-heading strong{font-size:14px;max-width:120px}
 .autopilot-settings .setting-summary{font-size:11px}
 .autopilot-settings .rating-instruction{font-size:11px}
 .autopilot-settings .save-actions .button{min-height:38px}
 .autopilot-settings .save-actions{gap:8px}
 .autopilot-settings .exclusion-state{padding:5px 7px;font-size:11px}
}
'''
(root / 'page/autopilot-settings.css').write_text(css, encoding='utf-8')

# Ship CSS with the controls script, before native tab registration. An inline
# shadow style is applied synchronously and needs no request when the tab opens.
import json
with (root / 'page/autopilot-settings-controls.js').open('a', encoding='utf-8') as output:
    output.write('\nwindow.AutopilotSettingsCSS = ' + json.dumps(css, ensure_ascii=True) + ';\n')
